# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build_And_Push_image
  displayName: Build & Push image
  jobs:
  - job: Build_And_Push
    displayName: Build & Push
    pool:
      vmImage: ubuntu-latest
    steps:   
    - task: Docker@2
      displayName: Build & Push an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'baneeishaque/gp-vnc-tint2-pcmanfm-zsh-as-gh-chrome-idea-pycharm-anaconda3-hb-scrcpy-r-littler-packrat-jupyter-lfs'
        command: 'buildAndPush'
        Dockerfile: '.gitpod.Dockerfile'
        tags: 'latest'